### ISSUE TITLE
Doesn't take care of "Off delay" switch option

### ISSUE THREAD

**Issue by BabaIsYou** [J0hnMatrix/domoticz-tplink-hs100-hs110-v2#1]
It seems that the switch doesn't take care of the "off Delay" configuration option in Domoticz.

My switch is configured to automatically come "Off" after 20 seconds :
Off Delay: 20 (Seconds) 0 = Disabled

But it seems that it does nothing (it works perfectly with a RF433 switch with RFXCom.

There is no action to switch it off after the 20s in log file.

**Comment by J0hnMatrix** [comment]
You should stop using this plugin as it not anymore maintained, I suggest you to try the official one that is compatible with both v1 and v2 smartplugs (and have other nice features like power reports, etc...):
https://github.com/lordzurp/domoticz-tplink-smartplug

**Comment by BabaIsYou** [comment]
Thanks for answer

Le 30 juin 2021 à 14:18, J0hnMatrix ***@***.***> a écrit :

﻿

You should stop using this plugin as it not anymore maintained, I suggest you to try the official one that is compatible with both v1 and v2 smartplugs (and have other nice features like power reports, etc...):
https://github.com/lordzurp/domoticz-tplink-smartplug
